name: JSON check

on:
  push:
    branches:
      - main
  workflow_dispatch:    

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: json-syntax-check
        uses: limitusus/json-syntax-check@v2
        with:
          pattern: "\\.json$"
      
      - name: push
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.BOT }}
          cname: store.win11react.com
          publish_dir: ./
